[package]
name = "PLAP_assignment"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand="0.8.5"
fltk="1.3"

[[bin]]
name = "calculator_gui"
path = "src/calculator_gui.rs"